'use client';

import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import Sidebar from '../components/Sidebar';
import { runFullValidation } from '../lib/validationEngine';
import { sampleWithIssues, sampleClean } from '../lib/sampleData';
import { MdPictureAsPdf, MdAutoAwesome, MdCheckCircle, MdError } from 'react-icons/md';
import jsPDF from 'jspdf';

export default function ReportPage() {
    const [aiReport, setAiReport] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [validationResults, setValidationResults] = useState(null);
    const [selectedSample, setSelectedSample] = useState('issues');

    // Run validation + call AI
    const handleGenerateReport = async () => {
        setIsGenerating(true);
        setAiReport('');

        // Step 1: Run validation
        const data = selectedSample === 'issues' ? sampleWithIssues : sampleClean;
        const results = runFullValidation(data);
        setValidationResults(results);

        // Step 2: Call AI API
        try {
            const response = await fetch('/api/analyze', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ validationResults: results }),
            });

            const data = await response.json();

            if (data.success) {
                setAiReport(data.report);
            } else {
                setAiReport('⚠️ Failed to generate AI report. Check your API key.');
            }
        } catch (error) {
            setAiReport('⚠️ Error connecting to AI service. Make sure the server is running.');
        }

        setIsGenerating(false);
    };

    // Download PDF
    const handleDownloadPDF = () => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Title
        doc.setFontSize(20);
        doc.setTextColor(59, 130, 246);
        doc.text('CAD Validation Report', pageWidth / 2, 20, { align: 'center' });

        // Subtitle
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text('Generated by CAD Validator AI', pageWidth / 2, 28, { align: 'center' });
        doc.text(new Date().toLocaleString(), pageWidth / 2, 34, { align: 'center' });

        // Line separator
        doc.setDrawColor(59, 130, 246);
        doc.line(20, 38, pageWidth - 20, 38);

        // Summary stats
        if (validationResults) {
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text('Validation Summary', 20, 48);
            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            doc.text(`Components Analyzed: ${validationResults.totalComponents}`, 20, 56);
            doc.text(`Total Issues: ${validationResults.totalIssues}`, 20, 62);
            doc.text(`Errors: ${validationResults.errors} | Warnings: ${validationResults.warnings}`, 20, 68);
            doc.text(`Status: ${validationResults.passed ? 'PASSED' : 'FAILED'}`, 20, 74);
        }

        // AI Report content
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text('AI Analysis', 20, 88);

        doc.setFontSize(9);
        doc.setTextColor(40, 40, 40);

        // Split report text into lines that fit the page
        const cleanReport = aiReport.replace(/[#*]/g, '').replace(/\n\n/g, '\n');
        const lines = doc.splitTextToSize(cleanReport, pageWidth - 40);

        let yPos = 96;
        lines.forEach((line) => {
            if (yPos > 280) {
                doc.addPage();
                yPos = 20;
            }
            doc.text(line, 20, yPos);
            yPos += 5;
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('CAD Validator AI — AI-Driven Design Intelligence', pageWidth / 2, 290, { align: 'center' });

        doc.save('CAD_Validation_Report.pdf');
    };

    return (
        <div className="app-layout">
            <Sidebar />
            <main className="main-content">
                <div className="page-header">
                    <h1 className="page-title">Validation Report</h1>
                    <p className="page-subtitle">AI-powered design analysis and compliance report</p>
                </div>

                {/* Controls */}
                <div className="glass-card" style={{ marginBottom: '24px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '16px', flexWrap: 'wrap' }}>
                        <select
                            value={selectedSample}
                            onChange={(e) => { setSelectedSample(e.target.value); setAiReport(''); setValidationResults(null); }}
                            style={{
                                padding: '10px 12px', borderRadius: '8px',
                                background: 'var(--bg-card)', color: 'var(--text-primary)',
                                border: '1px solid var(--border-color)', fontSize: '14px',
                                cursor: 'pointer', outline: 'none',
                            }}
                        >
                            <option value="issues">🔴 Sample Design — Has Errors</option>
                            <option value="clean">🟢 Sample Design — All Good</option>

                        </select>

                        <button
                            className="btn btn-primary"
                            onClick={handleGenerateReport}
                            disabled={isGenerating}
                        >
                            {isGenerating ? (
                                <>⏳ AI is analyzing...</>
                            ) : (
                                <><MdAutoAwesome /> Generate AI Report</>
                            )}
                        </button>

                        {aiReport && (
                            <button className="btn btn-outline" onClick={handleDownloadPDF}>
                                <MdPictureAsPdf /> Download PDF
                            </button>
                        )}
                    </div>
                </div>

                {/* Validation Summary */}
                {validationResults && (
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px', marginBottom: '24px' }}>
                        <div className="glass-card" style={{ textAlign: 'center' }}>
                            <p style={{ color: 'var(--text-muted)', fontSize: '12px', marginBottom: '4px' }}>COMPONENTS</p>
                            <p style={{ fontSize: '28px', fontWeight: '700' }}>{validationResults.totalComponents}</p>
                        </div>
                        <div className="glass-card" style={{ textAlign: 'center' }}>
                            <p style={{ color: 'var(--text-muted)', fontSize: '12px', marginBottom: '4px' }}>ERRORS</p>
                            <p style={{ fontSize: '28px', fontWeight: '700', color: 'var(--accent-red)' }}>{validationResults.errors}</p>
                        </div>
                        <div className="glass-card" style={{ textAlign: 'center' }}>
                            <p style={{ color: 'var(--text-muted)', fontSize: '12px', marginBottom: '4px' }}>WARNINGS</p>
                            <p style={{ fontSize: '28px', fontWeight: '700', color: 'var(--accent-yellow)' }}>{validationResults.warnings}</p>
                        </div>
                        <div className="glass-card" style={{ textAlign: 'center' }}>
                            <p style={{ color: 'var(--text-muted)', fontSize: '12px', marginBottom: '4px' }}>STATUS</p>
                            <p style={{ fontSize: '28px', fontWeight: '700', color: validationResults.passed ? 'var(--accent-green)' : 'var(--accent-red)' }}>
                                {validationResults.passed ? '✓ PASS' : '✕ FAIL'}
                            </p>
                        </div>
                    </div>
                )}

                {/* AI Report */}
                {isGenerating && (
                    <div className="glass-card" style={{ textAlign: 'center', padding: '60px' }}>
                        <p style={{ fontSize: '18px', marginBottom: '12px' }}>🤖 AI is analyzing your design...</p>
                        <p style={{ color: 'var(--text-muted)' }}>Using Groq LLM to generate a comprehensive report</p>
                    </div>
                )}

                {aiReport && (
                    <div className="glass-card">
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
                            <MdAutoAwesome style={{ color: 'var(--accent-purple)', fontSize: '20px' }} />
                            <h3 style={{ fontSize: '16px', fontWeight: '600' }}>AI Analysis Report</h3>
                        </div>
                        <div className="ai-report-content">
                            <ReactMarkdown>{aiReport}</ReactMarkdown>
                        </div>

                    </div>
                )}
            </main>
        </div>
    );
}